AWS Lambda Docs
ntuscse/docs pull request #13
Opened 2022-10-14 10:57 UTC by aryans1204

Added docs for AWS Lambda

2022-10-14 12:27 UTC, chanbakjsd requested changes
Overall, this is a really comprehensive article on AWS Lambda.
Other than the trivial cosmetic changes I've added comments on, this article could use some shortening as it might be too verbose for someone to refer to easily.
Can you also replace the headings with subheadings (`##` or `###` instead of `#`)? That'll generate sections on the sidebar which will help navigation.

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +patches. As opposed to IaaS(Infrastructure as a Service) models, where users must prepurchase units of compute like VM's and perform autoscaling and load balancing
```suggestion
patches. As opposed to IaaS (Infrastructure as a Service) models, where users must prepurchase units of compute like VM's and perform autoscaling and load balancing
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +that the app is only launched when an event(API request, or a client request) triggers the app to run, and the cloud provider will dynamically handle the resource
```suggestion
that the app is only launched when an event (API request, or a client request) triggers the app to run, and the cloud provider will dynamically handle the resource
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +Now that we've takena look at some functionalities offered by AWS Lambda, how exactly does it work, and how can you, as an app or API developer leverage the
```suggestion
Now that we've taken a look at some functionalities offered by AWS Lambda, how exactly does it work, and how can you, as an app or API developer leverage the 
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +functionlities of AWS Lambda?
```suggestion
functionalities of AWS Lambda?
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +* Fully managed- they are managed by the cloud provider, which means the app developer does not have to create Container Images or monitor the health of the containers.
```suggestion
* Stateless - any changes made to the container during execution are not saved after container is shut down. They do not store state.
* Ephemeral - they run for a very short time during execution and do not store any state
* Event-Triggered - they run only when the associated event triggers them(we'll look at this in depth later in the doc)
* Fully managed - they are managed by the cloud provider, which means the app developer does not have to create Container Images or monitor the health of the containers.
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +#   Writing the Lambda function
```suggestion
# Writing the Lambda function
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +is an actual function, that represents the logic of the task you want to peform, essentially, in the function body you will code what you want the Lambda function
```suggestion
is an actual function, that represents the logic of the task you want to perform, essentially, in the function body you will code what you want the Lambda function
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +The function can be given any name, in this case we just call it event_handler and define it just like any other function. Each function must take as argument
```suggestion
The function can be given any name, in this case we just call it `lambda_handler` and define it just like any other function. Each function must take as argument
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +# .  Deploying the Lambda function
```suggestion
# Deploying the Lambda function
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +8. Now that your Lambda function is created, we need to add an EVent rule which dictates when the Lambda function will be triggered. Click on your Lamda function
```suggestion
8. Now that your Lambda function is created, we need to add an event rule which dictates when the Lambda function will be triggered. Click on your Lambda function
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +instances and Testing the Lambda function top see if the function actually stops the instances or not. It is a best practice to thoroughly test your Lambda
```suggestion
instances and Testing the Lambda function above to see if the function actually stops the instances. It is a best practice to thoroughly test your Lambda
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +go ahead and chooe Schedule expression.
```suggestion
go ahead and choose Schedule expression.
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +13. At this point, your AS Lambda function is complete, and ready to be deployed. Head back to the Lambda funtion page, and clikc on Deploy. Note: you may or may not
```suggestion
13. At this point, your AWS Lambda function is complete, and ready to be deployed. Head back to the Lambda function page, and click on Deploy. Note: you may or may not
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +be able to actually deploy the LAmbda function based on the level of permissions provided to your IAM identity. Contact your System Administrator for more information.
```suggestion
be able to actually deploy the Lambda function based on the level of permissions provided to your IAM identity. Contact your System Administrator for more information.
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +# . Why and When to use AWS Lambda?
```suggestion
# Why and When to use AWS Lambda?
```

2022-10-14 12:27 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +
Excessive whitespaces.

2022-10-18 01:07 UTC, chanbakjsd requested changes
In addition to the previous review, there are still some minor cosmetic issues that needs to be fixed.

2022-10-18 01:07 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +##   Writing the Lambda function
```suggestion
## Writing the Lambda function
```

2022-10-18 01:07 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +##   Deploying the Lambda function
```suggestion
## Deploying the Lambda function
```

2022-10-20 13:37 UTC, chanbakjsd reviewed
Just a typographical error.
An idea to expand on the docs in the future is how to use AWS Lambda (common operations).

2022-10-20 13:37 UTC, chanbakjsd commented on docs/aws/aws-lambda.mdx
> +The documentation is written from the persepctive of a reader who is completely new to serverless computing and AWS Lambda, and so there are some sections that may
```suggestion
The documentation is written from the perspective of a reader who is completely new to serverless computing and AWS Lambda, and so there are some sections that may
```

2022-10-20 14:11 UTC, chanbakjsd approved these changes
This is a good start for the document.

2022-10-20 14:12 UTC, aryans1204 commented
Merging then

2022-10-20 14:15 UTC, RealDyllon approved these changes

2022-10-20 14:22 UTC, merged